### ISSUE TITLE
Firebase Cloud Messaging respond back with No 'image' !

### ISSUE THREAD

**Issue by grafpix** [grafpix/grafpix#1]
**Image not showing when i receive notification from the cloud**

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

exports.triggerUpdate = functions.database.ref('Database').onWrite((snapshot, context) => {
    const authUser = context.auth;
    const payload = {
        "notification": {
            "title": "Database Updated by " + authUser.uid,
            "body": "Application Notification Center - testing",
            "image": "https://some-working-url/with_valid_image_link.jpg",    // <--- image not received 
            "clickAction": "FLUTTER_NOTIFICATION_CLICK"
        }
    };
    return admin.messaging().sendToDevice("uF7r3XXXXXXXXXXXXSomeDeviceTokenId", payload);
});
```

**Comment by bicho19** [comment]
Check the documentation, try using imageUrl. 
https://firebase.google.com/docs/reference/admin/node/admin.messaging.Notification

**Comment by grafpix** [comment]
> Check the documentation, try using imageUrl.
> https://firebase.google.com/docs/reference/admin/node/admin.messaging.Notification
  
I did , still not working.. no errors have been logged, here is a snippet of callback message
`{notification: {title: Database Updated by [authUser.uid], body: title Application Notification Center - testing}, data: {}}`
